name: Build solution and run tests
description: >-
  This action installs the .NET SDK with the version specified in the given `global.json` file and connects it to the
  specified NuGet feed. It then builds the given solution with the given run configuration. As an optional step, which
  is enabled by default, it runs all tests, collects code coverage of the given type and creates or updates an existing
  pull request comment with the test coverage.
inputs:
  configuration:
    description: 'The configuration to build the solution in. Defaults to "Release".'
    required: false
    default: 'Release'
  github-token:
    description: 'The GitHub token used to create and update the pull request comment.'
    required: true
  global-json-file:
    description: 'The path to the `global.json` file specifying the .NET SDK version to install.'
    required: false
    default: 'global.json'
  install-playwright:
    description: 'Whether to install Playwright browsers. Defaults to "false".'
    required: false
    default: 'false'
  nuget-auth-token:
    description: 'The token used to authenticate to the custom NuGet feed specified in `nuget-feed-uri`.'
    required: true
  nuget-feed-uri:
    description: 'The URI of the custom NuGet feed to connect to.'
    required: true
  playwright-projects:
    description: 'Comma-separated list of test project names (not paths) that use Playwright (e.g., "MyApp.Tests.E2E,MyApp.Integration.Tests")'
    required: false
    default: ''
  run-tests:
    description: 'Whether to run tests. Defaults to "true". Any other value disables the tests.'
    required: false
    default: 'true'
  solution-path:
    description: 'The path to the .NET solution file. Defaults to the root directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
      with:
        global-json-file: ${{ inputs.global-json-file }}
        source-url: ${{ inputs.nuget-feed-uri }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.nuget-auth-token }}
    - name: Restore dependencies
      shell: bash
      run: |
        dotnet restore \
        -p:ArtifactsPath=${{ github.workspace }}/artifacts \
        ${{ inputs.solution-path }}
    - name: Build
      shell: bash
      run: |
        dotnet build -c ${{ inputs.configuration }} \
        --no-restore \
        -p:ArtifactsPath=${{ github.workspace }}/artifacts \
        ${{ inputs.solution-path }}
    - name: Install Playwright browsers
      if: ${{ inputs.run-tests == 'true' && inputs.install-playwright == 'true' }}
      shell: pwsh
      run: |
        $projects = "${{ inputs.playwright-projects }}".Split(",") | Where-Object { $_ -ne "" }
        $configuration = "${{ inputs.configuration }}".ToLower()

        foreach ($project in $projects) {
          $project = $project.Trim()
          $playwrightScript = Join-Path "${{ github.workspace }}" "artifacts/bin/$project/$configuration/playwright.ps1"

          if (Test-Path $playwrightScript) {
            Write-Host "Installing Playwright browsers for $project..."
            & $playwrightScript install
          } else {
            Write-Error "Playwright script not found at: $playwrightScript"
            exit 1
          }
        }
    - name: Test
      if: ${{ inputs.run-tests == 'true' }}
      shell: bash
      run: |
        dotnet test -c ${{ inputs.configuration }} \
        --no-build \
        --verbosity normal \
        --solution ${{ inputs.solution-path }} \
        -p:ArtifactsPath=${{ github.workspace }}/artifacts \
        --coverage \
        --coverage-output-format cobertura \
        --coverage-output coverage.cobertura.xml \
        --results-directory ./coverage
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@ee0ae774f6d3afedcbd1683c1ab21b83670bdf8e # v5.5.1
      if: ${{ inputs.run-tests == 'true' }}
      with:
        reports: '**/coverage/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: ${{ inputs.run-tests == 'true' }}
      with:
        filename: 'coveragereport/Cobertura.xml'
        badge: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      if: ${{ inputs.run-tests == 'true' }}
      with:
        header: 'codecoverage'
        recreate: true
        path: code-coverage-results.md
