<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.4.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SelfTest\SelfTest.csproj" />
  </ItemGroup>
</Project>
